name: Deploy Container Infrastructure Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Opentofu
        uses: opentofu/setup-opentofu@v1

      - name: Load SSH key files
        run: |
          mkdir -p ~/keys
          echo "$UPCLOUD_SSH_PRIVATE_KEY" > ~/keys/id_ed25519
          chmod 644 ~/keys/id_ed25519
          echo "$UPCLOUD_SSH_PUBLIC_KEY" > ~/keys/id_ed25519.pub
          chmod 644 ~/keys/id_ed25519.pub

      - name: Opentofu prep
        run: |
          cd infra
          tofu init
          tofu validate

      - name: Opentofu plan
        run: |
          cd infra
          tofu plan -out=tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}

      - name: Opentofu apply
        run: |
          cd infra
          tofu apply tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
