name: Deploy Container Infrastructure Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Opentofu
        uses: opentofu/setup-opentofu@v1

      - name: Opentofu prep
        run: |
          opentofu init
          opentofu validate

      - name: Opentofu plan
        run: |
          opentofu plan -out=tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}

      - name: Opentofu apply
        run: |
          opentofu apply tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
