name: Deploy Container Infrastructure Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Setup Terraform Cloud credentials
        run: |
          cat > ~/.terraformrc <<EOF
          credentials "app.terraform.io" {
            token = "${{ secrets.TF_API_TOKEN }}"
          }
          EOF
          chmod 0600 ~/.terraformrc

      - name: Load SSH key files
        run: |
          mkdir -p ~/keys
          echo "${{ secrets.UPCLOUD_SSH_PRIVATE_KEY }}" > ~/keys/id_ed25519
          chmod 600 ~/keys/id_ed25519
          echo "${{ secrets.UPCLOUD_SSH_PUBLIC_KEY }}" > ~/keys/id_ed25519.pub
          chmod 644 ~/keys/id_ed25519.pub

      - name: OpenTofu Init
        run: |
          cd infra
          tofu init

      - name: OpenTofu Validate
        run: |
          cd infra
          tofu validate

      - name: OpenTofu Plan
        run: |
          cd infra
          tofu plan -out=tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}

      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra
          tofu apply tofu.plan
        env:
          UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
          UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}